#Label Encoder,Onehot Encoder

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame({'color':['red','green','blue','red','blue'],'level':['High','Low','High','Medium','Low'],'city':['Bangalore','Haveri','Bangalore','Hubli','Hubli'],'purchased':['Yes','Yes','No','Yes','No']})

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [ ]:
label_encoder=LabelEncoder()


In [ ]:
label_encoder.fit_transform(df['purchased'])
label_encoder.transform(['Yes'])


array([1])

In [ ]:
'''label_encoder.fit_transform(df[['purchased','level']])
ValueError: y should be a 1d array, got an array of shape (5, 2) instead.
'''

"label_encoder.fit_transform(df[['purchased','level']])\nValueError: y should be a 1d array, got an array of shape (5, 2) instead.\n"

In [ ]:
'''label_encoder.transform(['Yess'])
ValueError: y contains previously unseen labels: 'Yess'
'''

"label_encoder.transform(['Yess'])\nValueError: y contains previously unseen labels: 'Yess'\n"

In [ ]:
label_encoder.transform(['Yes','Yes'])

array([1, 1])

In [ ]:
'''label_encoder.transform([['Yes','Yes']])
ValueError: y should be a 1d array, got an array of shape (1, 2) instead.
'''

"label_encoder.transform([['Yes','Yes']])\nValueError: y should be a 1d array, got an array of shape (1, 2) instead.\n"

#ONEHOT ENCODER

In [ ]:
one_hot_encoder=OneHotEncoder()

In [ ]:
res=one_hot_encoder.fit_transform(df[['color','city']])
res1=one_hot_encoder.transform([['green','Haveri']])
res1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2 stored elements and shape (1, 6)>

In [ ]:
'''
res=one_hot_encoder.fit_transform(df['color'])
res
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
'''

"\nres=one_hot_encoder.fit_transform(df['color'])\nres\nValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.\n"

In [ ]:
res=res.toarray()
res

array([[0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.]])

In [ ]:
'''
res1=one_hot_encoder.transform(['green','Haver'])
ValueError: Expected 2D array, got 1D array instead:
array=['green' 'Haver'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
'''

"\nres1=one_hot_encoder.transform(['green','Haver'])\nValueError: Expected 2D array, got 1D array instead:\narray=['green' 'Haver'].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n"

In [ ]:
'''
res1=one_hot_encoder.transform(['green'])

ValueError: Expected 2D array, got 1D array instead:
array=['green'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample
'''

"\nres1=one_hot_encoder.transform(['green'])\n\nValueError: Expected 2D array, got 1D array instead:\narray=['green'].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample\n"

In [ ]:
'''
res1=one_hot_encoder.transform([['green']])
ValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.
'''

"\nres1=one_hot_encoder.transform([['green']])\nValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.\n"

In [ ]:
res_cols=one_hot_encoder.get_feature_names_out()
res_cols

array(['color_blue', 'color_green', 'color_red', 'city_Bangalore',
       'city_Haveri', 'city_Hubli'], dtype=object)

In [ ]:
pd.DataFrame(res,columns=res_cols)

color_blue  color_green  color_red  city_Bangalore  city_Haveri  city_Hubli
0         0.0          0.0        1.0             1.0          0.0         0.0
1         0.0          1.0        0.0             0.0          1.0         0.0
2         1.0          0.0        0.0             1.0          0.0         0.0
3         0.0          0.0        1.0             0.0          0.0         1.0
4         1.0          0.0        0.0             0.0          0.0         1.0

In [ ]:
one_hot_encoder=OneHotEncoder(sparse_output=False)

In [ ]:
res=one_hot_encoder.fit_transform(df[['color','city']])

In [ ]:
one_hot_encoder.fit(df[['color','city']])

OneHotEncoder(sparse_output=False)

In [ ]:
'''
one_hot_encoder.transform(df[['color']])
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- city
'''

"\none_hot_encoder.transform(df[['color']])\nValueError: The feature names should match those that were passed during fit.\nFeature names seen at fit time, yet now missing:\n- city\n"

In [ ]:
'''
one_hot_encoder.transform([['red']])
ValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.
'''

"\none_hot_encoder.transform([['red']])\nValueError: X has 1 features, but OneHotEncoder is expecting 2 features as input.\n"

In [ ]:
one_hot_encoder.transform([['red','Haveri']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0., 1., 0.]])

In [ ]:
'''
one_hot_encoder.transform([['redd','Haveri']])
ValueError: Found unknown categories ['Redd'] in column 0 during transform
'''

"\none_hot_encoder.transform([['redd','Haveri']])\nValueError: Found unknown categories ['Redd'] in column 0 during transform\n"

In [ ]:
one_hot_encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [ ]:
one_hot_encoder.fit_transform(df[['color','city']])

array([[0., 0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.]])

In [ ]:
one_hot_encoder.transform([['redd','Haveri']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 1., 0.]])

In [ ]:
one_hot_encoder.fit_transform(df[['color']])

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
one_hot_encoder.transform([['red'],['redd']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
one_hot_encoder.transform([['redd']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0.]])

#ORDINAL ENCODER

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df

color   level       city purchased
0    red    High  Bangalore       Yes
1  green     Low     Haveri       Yes
2   blue    High  Bangalore        No
3    red  Medium      Hubli       Yes
4   blue     Low      Hubli        No

In [ ]:
'''
ordinal=OrdinalEncoder(categories=['red','green','blue'])
ordinal.fit_transform(df['color'])
ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.
'''

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
'''
ordinal=OrdinalEncoder(categories=[['Bangalore','Haveri','Hubli'],['High','Medium','Low'],['red','green','blue'],['Yes','No']])
ordinal.fit_transform(df)
ValueError: Found unknown categories ['red', 'green', 'blue'] in column 0 during fit
'''

"\nordinal=OrdinalEncoder(categories=[['Bangalore','Haveri','Hubli'],['High','Medium','Low'],['red','green','blue'],['Yes','No']])\nordinal.fit_transform(df)\nValueError: Found unknown categories ['red', 'green', 'blue'] in column 0 during fit\n"

In [ ]:
ordinal=OrdinalEncoder(categories=[['red','green','blue'],['High','Medium','Low'],['Bangalore','Haveri','Hubli'],['Yes','No']])
ordinal.fit_transform(df)

array([[0., 0., 0., 0.],
       [1., 2., 1., 0.],
       [2., 0., 0., 1.],
       [0., 1., 2., 0.],
       [2., 2., 2., 1.]])

In [ ]:
'''
ordinal.transform([['red']])
ValueError: X has 1 features, but OrdinalEncoder is expecting 4 features as input.
'''

"\nordinal.transform([['red']])\nValueError: X has 1 features, but OrdinalEncoder is expecting 4 features as input.\n"

In [ ]:
ordinal.transform([['red','Low','Haveri','No']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0., 2., 1., 1.]])

#how to handle unknown values

In [ ]:
'''
ordinal=OrdinalEncoder(categories=[['red','green','blue']],handle_unknown='use_encoded_value')
values=ordinal.fit_transform(df[['color']])
ordinal.transform([['orange']])
TypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.
'''

"\nordinal=OrdinalEncoder(categories=[['red','green','blue']],handle_unknown='use_encoded_value')\nvalues=ordinal.fit_transform(df[['color']])\nordinal.transform([['orange']])\nTypeError: unknown_value should be an integer or np.nan when handle_unknown is 'use_encoded_value', got None.\n"

In [ ]:
'''
ordinal=OrdinalEncoder(categories=[['red','green','blue']],handle_unknown='use_encoded_value',unknown_value=0)
values=ordinal.fit_transform(df[['color']])
ordinal.transform([['orange']])
ValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.
'''

"\nordinal=OrdinalEncoder(categories=[['red','green','blue']],handle_unknown='use_encoded_value',unknown_value=0)\nvalues=ordinal.fit_transform(df[['color']])\nordinal.transform([['orange']])\nValueError: The used value for unknown_value 0 is one of the values already used for encoding the seen categories.\n"

In [ ]:
ordinal=OrdinalEncoder(categories=[['red','green','blue']],handle_unknown='use_encoded_value',unknown_value=-1)
values=ordinal.fit_transform(df[['color']])
ordinal.transform([['orange']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[-1.]])